server:
  port: 8071
spring:
  application:
    name: shop-user-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///shop-user?serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf-8
    username: root
    password: "12345"
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
